MVCFull/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCFull.Models
{
    public class Car
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        [Range(1920, 2020)]
        public int Year { get; set; }

        [EmailAddress]
        public string Email { get; set; }
    }

    public class VMCar
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        [Range(1920, 2020)]
        public int Year { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public bool Rented { get; set; }

        [DataType(DataType.DateTime, ErrorMessage = "Return date format is invalid")]
        public DateTime ReturnTime { get; set; }
    }
}

MVCFull/Controllers/CarController.cs
using MVCFull.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFull.Controllers
{
    public class CarController : Controller
    {
        static List<Car> myCars = new List<Car> { new Car { ID = 1, Make = "Honda", Model ="Accord", Year = 2010, Email = "accord@honda.com"},
                                                  new Car { ID = 2, Make = "Honda", Model ="Civic", Year = 2011, Email = "civic@honda.com"},
                                                  new Car { ID = 3, Make = "Honda", Model ="CRV", Year = 2012, Email = "crv@honda.com"},
        };

        // GET: Car
        public ActionResult Index()
        {
            return View(myCars);
        }

        // GET: Car/Details/5
        public ActionResult Details(int id)
        {
            Car theCar = myCars.Find(car => car.ID == id);
            VMCar vmCar = new VMCar
            {
                ID = theCar.ID,
                Email = theCar.Email,
                Make = theCar.Make,
                Model = theCar.Model,
                Rented = true,
                ReturnTime = DateTime.Now.AddDays(1),
                Year = theCar.Year
            };
            return View(vmCar);
        }

        // GET: Car/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Car/Create
        [HttpPost]
        public ActionResult Create(Car myCar)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    myCar.ID = myCars.Count + 1;
                    myCars.Add(myCar);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Car/Edit/5
        public ActionResult Edit(int id)
        {
            Car theCar = myCars.Find(car => car.ID == id);
            return View(theCar);
        }

        // POST: Car/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Car updatedCar)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    int index = myCars.FindIndex(car => car.ID == id);
                    if (index != -1)
                    {
                        myCars[index] = updatedCar;
                        return RedirectToAction("Index");
                    }
                    return View();
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Car/Delete/5
        public ActionResult Delete(int id)
        {
            Car theCar = myCars.Find(car => car.ID == id);
            return View(theCar);
        }

        // POST: Car/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    myCars.RemoveAt(id - 1);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCFull/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFull.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCFull/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFull.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        // GET: Test/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Test/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Test/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Test/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Test/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCFull/Views/Shared/_Car.cshtml
@model MVCFull.Models.Car

<tr>
    <td>
        @Html.DisplayFor(item => item.Make)
    </td>
    <td>
        @Html.DisplayFor(item => item.Model)
    </td>
    <td>
        @Html.DisplayFor(item => item.Year)
    </td>
    <td>
        @Html.DisplayFor(item => item.Email)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Details", "Details", new { id = Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID })
    </td>
</tr>

MVCFull/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mohawk ASP.NET MVC 5 Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <img src="~/Content/mohawkCollegeLogoPrintHorizontalColour-689.jpg" />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("MyCars", "Index", "Car")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mohawk ASP.NET MVC 5 Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>